### ISSUE TITLE
Check for cycle in DAG

### ISSUE THREAD

**Issue by ChristianZimpelmann** [OpenSourceEconomics/dags#8]
### Current situation

- There is no explicit check for cycles in the DAG. 
-  If the functions contain a cycle, a ``networkx.exception.NetworkXUnfeasible:`` is raised which does not give further information about the cycle.

### Desired Situation

- Check for cycles already while DAG is built
- State the cycle(s) in the error message
 
### Proposed implementation
```
def _fail_if_dag_contains_cycle(dag):
    """Check for cycles in DAG"""
    cycles = list(nx.simple_cycles(dag))
    if len(cycles) > 0:
        raise ValueError(f"The DAG contains at least one cycle: {cycles}")

**Comment by janosg** [comment]
Sounds good!
